Repository BlindlyTeam/Blindly, pull requests merged in 2021-04, with the labels that each got.

#118 Matching interface functionalities
  .codeclimate.yml
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/blindly/match/MatchActivityTest.kt
  app/src/androidTest/java/ch/epfl/sdp/blindly/match/ProfileTest.kt
  app/src/androidTest/java/ch/epfl/sdp/blindly/match/TestMainToMatch.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MainScreen.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MatchPageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/CardStackAdapter.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/MatchActivity.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/Profile.kt
  app/src/main/res/drawable/like_green.xml
  app/src/main/res/drawable/rewind_blue.xml
  app/src/main/res/drawable/skip_red.xml
  app/src/main/res/layout/activity_match.xml
  app/src/main/res/layout/fragment_match_page.xml
  app/src/main/res/layout/item_profile.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: actual: 13h, actual: 3h

#136 documentation richard
  app/src/main/java/ch/epfl/sdp/blindly/LocationPermissionActivity.kt
  app/src/main/java/ch/epfl/sdp/blindly/location/AndroidLocationService.kt
  app/src/main/java/ch/epfl/sdp/blindly/location/LocationService.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MatchPageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/CardStackAdapter.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/MatchActivity.kt
  app/src/main/java/ch/epfl/sdp/blindly/match/Profile.kt
Labels: actual: 1h

#137 Add KDoc
  app/src/main/java/ch/epfl/sdp/blindly/EditProfile.kt
  app/src/main/java/ch/epfl/sdp/blindly/SplashScreen.kt
  app/src/main/java/ch/epfl/sdp/blindly/ViewModelFactory.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MainScreen.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MatchPageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/MessagePageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/ViewPagerAdapter.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/profile/ProfilePageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/profile/ProfilePageViewModel.kt
  app/src/main/java/ch/epfl/sdp/blindly/settings/Settings.kt
  app/src/main/java/ch/epfl/sdp/blindly/settings/SettingsShowMe.kt
  app/src/main/java/ch/epfl/sdp/blindly/user/User.kt
  app/src/main/java/ch/epfl/sdp/blindly/user/UserCache.kt
  app/src/main/java/ch/epfl/sdp/blindly/user/UserHelper.kt
  app/src/main/java/ch/epfl/sdp/blindly/user/UserRepository.kt
Labels: actual: 1h, documentation

#150 Change test in profile page, they now work!
  .codeclimate.yml
  app/src/androidTest/java/ch/epfl/sdp/blindly/main_screen/ProfilePageTest.kt
  app/src/androidTest/java/ch/epfl/sdp/blindly/main_screen/ViewPagerAdapterTest.kt
  app/src/test/java/ch/epfl/sdp/blindly/ProfilePageViewModelUnitTest.kt
  app/src/test/java/ch/epfl/sdp/blindly/UserUnitTest.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: actual: 1h

#153 Add location into firebase
  app/build.gradle
  app/src/androidTest/java/ch/epfl/sdp/blindly/fake_module/FakeUserCacheModule.kt
  app/src/main/java/ch/epfl/sdp/blindly/location/AndroidLocationService.kt
  app/src/main/java/ch/epfl/sdp/blindly/main_screen/profile/ProfilePageFragment.kt
  app/src/main/java/ch/epfl/sdp/blindly/profile_setup/ProfileFinished.kt
  app/src/main/java/ch/epfl/sdp/blindly/profile_setup/ProfilePassions.kt
  app/src/main/java/ch/epfl/sdp/blindly/settings/SettingsLocation.kt
  app/src/main/java/ch/epfl/sdp/blindly/user/User.kt
  app/src/test/java/ch/epfl/sdp/blindly/UserCacheUnitTest.kt
  app/src/test/java/ch/epfl/sdp/blindly/UserUnitTest.kt
Labels: actual: 5h
